CREATE TABLE IF NOT EXISTS product_list (id INTEGER, product_name TEXT, price INTEGER, tax INTEGER);

INSERT INTO product_list (id, product_name, price, tax) VALUES (1, 'Bacitracin Zinc and Polymyxin B Sulfate', 13, 4);
INSERT INTO product_list (id, product_name, price, tax) VALUES (2, 'Ceftriaxone Sodium', 63, 5);
INSERT INTO product_list (id, product_name, price, tax) VALUES (3, 'Lisinopril and Hydrochlorothiazide', 77, 2);
INSERT INTO product_list (id, product_name, price, tax) VALUES (4, 'ADENOSINE', 29, 1);
INSERT INTO product_list (id, product_name, price, tax) VALUES (5, 'Pulmo Tartarus 6/8', 10, 4);
INSERT INTO product_list (id, product_name, price, tax) VALUES (6, 'modafinil', 46, 2);
INSERT INTO product_list (id, product_name, price, tax) VALUES (7, 'Furosemide', 28, 1);
INSERT INTO product_list (id, product_name, price, tax) VALUES (8, 'Dextroamphetamine Saccharate, Amphetamine Aspartate, Dextroamphetamine Sulfate and Amphetamine Sulfate', 71, 2);
INSERT INTO product_list (id, product_name, price, tax) VALUES (9, 'CETIRIZINE HYDROCHLORIDE', 17, 1);
INSERT INTO product_list (id, product_name, price, tax) VALUES (10, 'Amoxicillin', 54, 2);
INSERT INTO product_list (id, product_name, price, tax) VALUES (11, 'Aluminum Zirconium Trichlorohydrex Gly', 55, 4);
INSERT INTO product_list (id, product_name, price, tax) VALUES (12, 'DIPHENHYDRAMINE HYDROCHLORIDE', 79, 4);
INSERT INTO product_list (id, product_name, price, tax) VALUES (13, 'Hydrocortisone Silicone', 94, 4);
INSERT INTO product_list (id, product_name, price, tax) VALUES (14, 'Triclosan', 39, 3);
INSERT INTO product_list (id, product_name, price, tax) VALUES (15, 'SODIUM MONOFLUOROPHOSPHATE', 69, 1);
INSERT INTO product_list (id, product_name, price, tax) VALUES (16, 'Mineral oil, petrolatum, phenylephrine hcl', 67, 4);
INSERT INTO product_list (id, product_name, price, tax) VALUES (17, 'Acetaminophen', 37, 5);
INSERT INTO product_list (id, product_name, price, tax) VALUES (18, 'triazolam', 17, 5);
INSERT INTO product_list (id, product_name, price, tax) VALUES (19, 'METHOTREXATE SODIUM', 79, 4);
INSERT INTO product_list (id, product_name, price, tax) VALUES (20, 'DIMETHICONE', 11, 5);
INSERT INTO product_list (id, product_name, price, tax) VALUES (21, 'Ketotifen Fumarate', 78, 4);
INSERT INTO product_list (id, product_name, price, tax) VALUES (22, 'bupropion hydrochloride', 4, 4);
INSERT INTO product_list (id, product_name, price, tax) VALUES (23, 'Morphine Sulfate', 92, 3);
INSERT INTO product_list (id, product_name, price, tax) VALUES (24, 'pegvisomant', 61, 5);
INSERT INTO product_list (id, product_name, price, tax) VALUES (25, 'Carbidopa and levodopa', 35, 2);
INSERT INTO product_list (id, product_name, price, tax) VALUES (26, 'zidovudine', 95, 2);
INSERT INTO product_list (id, product_name, price, tax) VALUES (27, 'Wingscale', 22, 2);
INSERT INTO product_list (id, product_name, price, tax) VALUES (28, 'Naratriptan', 12, 1);
INSERT INTO product_list (id, product_name, price, tax) VALUES (29, 'Valsartan and Hydrochlorothiazide', 34, 4);
INSERT INTO product_list (id, product_name, price, tax) VALUES (30, 'OXYBENZONE', 49, 4);
INSERT INTO product_list (id, product_name, price, tax) VALUES (31, 'Diltiazem Hydrochloride', 71, 3);
INSERT INTO product_list (id, product_name, price, tax) VALUES (32, 'Diclofenac sodium and Misoprostol', 25, 2);
INSERT INTO product_list (id, product_name, price, tax) VALUES (33, 'Fentanyl Citrate', 58, 5);
INSERT INTO product_list (id, product_name, price, tax) VALUES (34, 'haloperidol', 97, 3);
INSERT INTO product_list (id, product_name, price, tax) VALUES (35, 'Acetaminophen, Aspirin and caffeine', 93, 4);
INSERT INTO product_list (id, product_name, price, tax) VALUES (36, 'Guaifenesin and Dextromethorphan Hydrobromide', 9, 1);
INSERT INTO product_list (id, product_name, price, tax) VALUES (37, 'Acetaminophen, Dextromethorphan HBr, Phenylephrine HCl', 100, 5);
INSERT INTO product_list (id, product_name, price, tax) VALUES (38, 'Diphenhydramine Hydrochloride', 80, 1);
INSERT INTO product_list (id, product_name, price, tax) VALUES (39, 'Ropinirole Hydrochloride', 93, 2);
INSERT INTO product_list (id, product_name, price, tax) VALUES (40, 'Ondansetron', 41, 2);
INSERT INTO product_list (id, product_name, price, tax) VALUES (41, 'BENZALKONIUM CHLORIDE, LIDOCAINE, BACITRACIN ZINC, NEOMYCIN SULFATE, POLYMYXIN B SULFATE, WATER, BENZOCAINE, ALCOHOL, IBUPROFEN, ACETAMINOPHEN, ASPIRIN', 85, 1);
INSERT INTO product_list (id, product_name, price, tax) VALUES (42, 'OYSTER SHELL CALCIUM CARBONATE, CRUDE - GOLDENSEAL - POTASSIUM DICHROMATE', 25, 5);
INSERT INTO product_list (id, product_name, price, tax) VALUES (43, 'carbidopa, levodopa and entacapone', 93, 4);
INSERT INTO product_list (id, product_name, price, tax) VALUES (44, 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 81, 2);
INSERT INTO product_list (id, product_name, price, tax) VALUES (45, 'Selenium Sulfide', 59, 3);
INSERT INTO product_list (id, product_name, price, tax) VALUES (46, 'Iodine Bush', 46, 5);
INSERT INTO product_list (id, product_name, price, tax) VALUES (47, 'Triclosan', 83, 1);
INSERT INTO product_list (id, product_name, price, tax) VALUES (48, 'Spironolactone', 48, 5);
INSERT INTO product_list (id, product_name, price, tax) VALUES (49, 'STAVUDINE', 72, 1);
INSERT INTO product_list (id, product_name, price, tax) VALUES (50, 'Mirtazapine', 85, 4);